version: '3.8'

services:
  spark-python-job:
    image: rihab26/spark_job:latest
    volumes:
      - ./data_sources:/app/data_sources:rw
      - ./Logs/spark-logs:/app/Logs/spark-logs:rw
    networks:
      - spark-network

  spark-history-server:
    image: rihab26/spark_history_server:latest
    volumes:
      - ./Logs/spark-logs:/tmp/spark-events:rw
    networks:
      - spark-network
    ports:
      - "18080:18080"

networks:
  spark-network:
    driver: bridge
