apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-history-server-volume
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/spark-events
